USE DB_INT_SOFTLAND

--===============================
--CREACION DE TABLAS
--===============================
CREATE TABLE AUXILIAR_CC(
	DEBITO VARCHAR(50) NOT NULL,
	CREDITO VARCHAR(50) NOT NULL,
	MONTO_DEBITO DECIMAL(28,8) NOT NULL
);

DROP TABLE AUXILIAR_CC;
--========================================================================================================================

CREATE TABLE CLIENTE(
	CLIENTE VARCHAR(20) PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(150) NOT NULL
);

DROP TABLE CLIENTE;
--========================================================================================================================
CREATE TABLE DOC_ELECTRONICO_PROC_DE(
	NUMERO_DOC VARCHAR(50) PRIMARY KEY NOT NULL,
	NIT_RECEPTOR VARCHAR(40) NOT NULL,
	CONTIENE_ERRORES VARCHAR(1) NULL,
	ERROR_WS VARCHAR(1) NOT NULL,
	ERROR_SOFTLAND VARCHAR(1) NOT NULL,
	ENVIADO VARCHAR(1) NOT NULL,
	TOTALGRAVADO DECIMAL(28,2) NULL,
	TOTALEXENTO DECIMAL(28,2) NULL,
	TOTALVENTA DECIMAL(28,2) NULL,
	TOTALDESCUENTOS DECIMAL(28,2) NULL,
	TOTALVENTANETA DECIMAL(28,2) NULL,
	TOTALIMPUESTO DECIMAL(28,2) NULL,
	TOTALCOMPROBANTE DECIMAL(28,2) NULL
);

DROP TABLE DOC_ELECTRONICO_PROC_DE;
--=========================================================================================================================

CREATE TABLE DOCUMENTOS_CC(
	APLICACION VARCHAR(249) NOT NULL,
	MONTO DECIMAL(28,8) NOT NULL,
	CLIENTE VARCHAR(20) NOT NULL,
	TIPO VARCHAR(3) NOT NULL PRIMARY KEY,
	DOCUMENTO VARCHAR(50) NOT NULL,
	CreateDate DATETIME NOT NULL,
	FECHA_DOCUMENTO DATETIME NOT NULL,
	TIPO_ASIENTO VARCHAR(4) NULL,
	MONEDA VARCHAR(4) NOT NULL
);

DROP TABLE DOCUMENTOS_CC;
--=========================================================================================================================

CREATE TABLE FACTURA(
	CLIENTE VARCHAR(20) NOT NULL,
	NOMBRE_CLIENTE VARCHAR(150) NULL,
	CONSECUTIVO VARCHAR(10) NULL,
	FACTURA VARCHAR(50) PRIMARY KEY NOT NULL,
	FECHA DATETIME NOT NULL,
	MODULO VARCHAR(4) NOT NULL,
	MONEDA_FACTURA VARCHAR(12) NOT NULL,
	RUBRO1 VARCHAR(50) NULL,
	ASIENTO_DOCUMENTO VARCHAR(10) NULL
);

DROP TABLE FACTURA
--========================================================================================================================

--===============================
--CONSULTAS SQL - STORE PROCEDURE
--===============================

--TRAER FACTURAS EN UN RANGO DE FECHAS
CREATE PROCEDURE SP_LISTAR_FACTURAS_DYNASOFT
	@fecha1 DATETIME,
	@fecha2 DATETIME
AS
BEGIN
	SELECT
		FACTURA.CLIENTE,
		FACTURA.NOMBRE_CLIENTE,
		FACTURA.CONSECUTIVO,
		FACTURA.FACTURA,
		FACTURA.FECHA,
		FACTURA.MODULO,
		DOC_ELECTRONICO_PROC_DE.NIT_RECEPTOR,
		DOC_ELECTRONICO_PROC_DE.CONTIENE_ERRORES,
		DOC_ELECTRONICO_PROC_DE.ERROR_WS,
		DOC_ELECTRONICO_PROC_DE.ERROR_SOFTLAND,
		DOC_ELECTRONICO_PROC_DE.ENVIADO,
		FACTURA.MONEDA_FACTURA,
		DOC_ELECTRONICO_PROC_DE.TOTALGRAVADO,
		DOC_ELECTRONICO_PROC_DE.TOTALEXENTO,
		DOC_ELECTRONICO_PROC_DE.TOTALVENTA,
		DOC_ELECTRONICO_PROC_DE.TOTALDESCUENTOS,
		DOC_ELECTRONICO_PROC_DE.TOTALVENTANETA,
		DOC_ELECTRONICO_PROC_DE.TOTALIMPUESTO,
		DOC_ELECTRONICO_PROC_DE.TOTALCOMPROBANTE,
		FACTURA.RUBRO1
	FROM FACTURA
		INNER JOIN DOC_ELECTRONICO_PROC_DE
			ON FACTURA.FACTURA = DOC_ELECTRONICO_PROC_DE.NUMERO_DOC
	WHERE FACTURA.FECHA >= @fecha1 AND FACTURA.FECHA <= @fecha2;
END

--========================================================================================================================
--TRAER NOTAS DE CREDITO EN UN RANGO DE FECHAS
CREATE PROCEDURE SP_LISTAR_NOTAS_CREDITO_DYNASOFT
	@fecha1 DATETIME,
	@fecha2 DATETIME
AS
BEGIN
	SELECT
		DOCUMENTOS_CC.CLIENTE,
		CLIENTE.NOMBRE,
		DOCUMENTOS_CC.TIPO,
		DOCUMENTOS_CC.DOCUMENTO,
		DOCUMENTOS_CC.CreateDate,
		DOCUMENTOS_CC.TIPO_ASIENTO,
		DOC_ELECTRONICO_PROC_DE.NIT_RECEPTOR,
		DOC_ELECTRONICO_PROC_DE.CONTIENE_ERRORES,
		DOC_ELECTRONICO_PROC_DE.ERROR_WS,
		DOC_ELECTRONICO_PROC_DE.ERROR_SOFTLAND,
		DOC_ELECTRONICO_PROC_DE.ENVIADO,
		DOCUMENTOS_CC.MONEDA,
		DOC_ELECTRONICO_PROC_DE.TOTALGRAVADO,
		DOC_ELECTRONICO_PROC_DE.TOTALEXENTO,
		DOC_ELECTRONICO_PROC_DE.TOTALVENTA,
		DOC_ELECTRONICO_PROC_DE.TOTALDESCUENTOS,
		DOC_ELECTRONICO_PROC_DE.TOTALVENTANETA,
		DOC_ELECTRONICO_PROC_DE.TOTALIMPUESTO,
		DOC_ELECTRONICO_PROC_DE.TOTALCOMPROBANTE
	FROM DOCUMENTOS_CC
		INNER JOIN CLIENTE
			ON DOCUMENTOS_CC.CLIENTE = CLIENTE.CLIENTE
		INNER JOIN DOC_ELECTRONICO_PROC_DE
			ON DOCUMENTOS_CC.DOCUMENTO = DOC_ELECTRONICO_PROC_DE.NUMERO_DOC
	WHERE DOCUMENTOS_CC.TIPO LIKE 'N/C' AND DOCUMENTOS_CC.CreateDate >= @fecha1 AND DOCUMENTOS_CC.CreateDate <= @fecha2;
END

--========================================================================================================================
--TRAER OTROS CREDITOS EN UN RANGO DE FECHAS
CREATE PROCEDURE SP_LISTAR_OTROS_CREDITOS_DYNASOFT
	@fecha1 DATETIME,
	@fecha2 DATETIME
AS
BEGIN
SELECT
	CLIENTE.CLIENTE,
	CLIENTE.NOMBRE,
	DOCUMENTOS_CC.TIPO,
	DOCUMENTOS_CC.DOCUMENTO,
	DOCUMENTOS_CC.FECHA_DOCUMENTO,
	DOCUMENTOS_CC.TIPO_ASIENTO,
	DOC_ELECTRONICO_PROC_DE.NIT_RECEPTOR,
	DOC_ELECTRONICO_PROC_DE.CONTIENE_ERRORES,
	DOC_ELECTRONICO_PROC_DE.ERROR_WS,
	DOC_ELECTRONICO_PROC_DE.ERROR_SOFTLAND,
	DOC_ELECTRONICO_PROC_DE.ENVIADO,
	DOCUMENTOS_CC.MONEDA,
	DOC_ELECTRONICO_PROC_DE.TOTALGRAVADO,
	DOC_ELECTRONICO_PROC_DE.TOTALEXENTO,
	DOC_ELECTRONICO_PROC_DE.TOTALVENTA,
	DOC_ELECTRONICO_PROC_DE.TOTALDESCUENTOS,
	DOC_ELECTRONICO_PROC_DE.TOTALVENTANETA,
	DOC_ELECTRONICO_PROC_DE.TOTALIMPUESTO,
	DOC_ELECTRONICO_PROC_DE.TOTALCOMPROBANTE,
	FACTURA.RUBRO1,
	DOCUMENTOS_CC.APLICACION,
	AUXILIAR_CC.CREDITO,
	DOCUMENTOS_CC.MONTO,
	AUXILIAR_CC.DEBITO

	FROM DOCUMENTOS_CC
		INNER JOIN CLIENTE 
			ON DOCUMENTOS_CC.CLIENTE = CLIENTE.CLIENTE
		INNER JOIN AUXILIAR_CC
			ON DOCUMENTOS_CC.DOCUMENTO = AUXILIAR_CC.CREDITO
		INNER JOIN DOC_ELECTRONICO_PROC_DE
			ON AUXILIAR_CC.DEBITO = DOC_ELECTRONICO_PROC_DE.NUMERO_DOC
		INNER JOIN FACTURA
			ON FACTURA.FACTURA = DOC_ELECTRONICO_PROC_DE.NUMERO_DOC
	WHERE DOCUMENTOS_CC.TIPO LIKE 'O/C' 
		AND DOCUMENTOS_CC.MONTO = AUXILIAR_CC.MONTO_DEBITO
		AND DOCUMENTOS_CC.CreateDate >= @fecha1 
		AND DOCUMENTOS_CC.CreateDate <= @fecha2;
END

--==================================================================================================
--===============================
--INSERTAR DATOS
--===============================

INSERT INTO AUXILIAR_CC(DEBITO,CREDITO,MONTO_DEBITO)
	VALUES('00100001010000001515','22012022',36146.54000000);

INSERT INTO CLIENTE(CLIENTE,NOMBRE)
	VALUES('CLI0353','TERRAPEZ SOCIEDAD ANONIMA');

INSERT INTO DOC_ELECTRONICO_PROC_DE(NUMERO_DOC,NIT_RECEPTOR,CONTIENE_ERRORES,ERROR_WS,ERROR_SOFTLAND,ENVIADO,TOTALGRAVADO,TOTALEXENTO,TOTALVENTA,TOTALDESCUENTOS,TOTALVENTANETA,TOTALIMPUESTO,TOTALCOMPROBANTE)
	VALUES('00100001010000001515','3101213755','N','N','N','S',60482.81,0.00,60482.81,0.00,60482.81,0.00,60482.81);

INSERT INTO DOCUMENTOS_CC(APLICACION,MONTO,CLIENTE,TIPO,DOCUMENTO,CreateDate,FECHA_DOCUMENTO,TIPO_ASIENTO,MONEDA)
	VALUES('SERVICIOS',60482.81000000,'CLI0353','N/C','00100001010000001515','2022-03-21 10:55:14.787','2022-03-21 00:00:00.000','CC','USD');

INSERT INTO FACTURA(CLIENTE,NOMBRE_CLIENTE,CONSECUTIVO,FACTURA,FECHA,MODULO,MONEDA_FACTURA,RUBRO1,ASIENTO_DOCUMENTO) 
	VALUES('CLI0353','TERRAPEZ SOCIEDAD ANONIMA','DE_FA','00100001010000001515','2022-03-21 10:55:13.000','FA','D','3406','FA00001963');

--==================================================================================================
--===============================
--EJECUCION DE PROCEDIMIENTOS ALMACENADOS
--===============================
EXEC SP_LISTAR_FACTURAS_DYNASOFT '2021-12-31 23:59:59.000', '2023-01-01 00:00:01.000';
EXEC SP_LISTAR_NOTAS_CREDITO_DYNASOFT '2021-12-31 23:59:59.000', '2023-01-01 00:00:01.000';
EXEC SP_LISTAR_OTROS_CREDITOS_DYNASOFT '2021-12-31 23:59:59.000', '2023-01-01 00:00:01.000';

--==================================================================================================
--===============================
--SELECT POR TABLAS
--===============================
SELECT * FROM AUXILIAR_CC;
SELECT * FROM CLIENTE;
SELECT * FROM DOC_ELECTRONICO_PROC_DE;
SELECT * FROM DOCUMENTOS_CC;
SELECT * FROM FACTURA; 

--==================================================================================================
--===============================
--ELIMINAR TODOS LOS DATOS
--===============================
DELETE FROM AUXILIAR_CC;
DELETE FROM CLIENTE;
DELETE FROM DOC_ELECTRONICO_PROC_DE;
DELETE FROM DOCUMENTOS_CC;
DELETE FROM FACTURA;

--==================================================================================================
--===============================
--ELIMINAR TODAS LAS TABLAS
--===============================
DROP TABLE FACTURA;
